
language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "nightly"
  - "pypy"

install:
 - pip install -r requirements-test.txt
 - pip install nose coverage

script:
 - make test

after_script:
 - coveralls

deploy:
  provider: pypi
  user: "gpodder"
  password:
    secure: "S0LtFa2Oz/srn78bQahypyMrp46jOHgucFYyGDGS+i9/fSar5zqyo+COX9vUsd3Lo7RRS00RPJDG5n/HSbH3x2LWUQRlltu51Qr8srC66lwjgkARjJbcbcyBBB+b0U8UYt5zns3CgJTWbrZ5tiN0Gtoq72ojfhiYuf54V4hRdlQ="
  on:
    tags: true
